name: Docker Image CI

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '30 17 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push amd64-addon-configurator
        uses: docker/build-push-action@v3
        with:
          context: ./configurator
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/amd64-addon-configurator:latest
          build-args: BUILD_FROM=ghcr.io/home-assistant/amd64-base:3.14
